name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        shell: bash
        run: |
          mkdir -p ~/nvim
          wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz -O nvim-linux64.tar.gz
          tar -C ~/nvim -xzf nvim-linux64.tar.gz --strip-components=1
          echo "$HOME/nvim/bin" >> $GITHUB_PATH
          ls -la ~/nvim/bin/

      - name: Neovim version
        run: nvim --version

      - name: Test Cache
        uses: actions/cache@v4
        with:
          path: .tests
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua', 'scripts/test') }}

      - name: Run tests
        run: |
          chmod +x scripts/test
          ./scripts/test

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: tag_name
        run: |
          echo "current_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation: true
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release v${{ steps.tag_name.outputs.current_version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          files: |
            LICENSE

      - name: Create Archives
        run: |
          mkdir -p sort-nvim
          cp -r lua plugin README.md LICENSE CHANGELOG.md sort-nvim/
          tar -czf sort-nvim-${{ steps.tag_name.outputs.current_version }}.tar.gz sort-nvim
          zip -r sort-nvim-${{ steps.tag_name.outputs.current_version }}.zip sort-nvim

      - name: Upload Archives to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            sort-nvim-${{ steps.tag_name.outputs.current_version }}.tar.gz
            sort-nvim-${{ steps.tag_name.outputs.current_version }}.zip
